export const initialProfile = {
  full_name: "Syarif Hidayatullah",
  role_title: "Web Developer & UI/UX Designer",
  bio: "Detail-oriented Web Developer with hands-on experience building scalable applications. Skilled in end-to-end development, from database architecture to UI/UX implementation, with a strong focus on delivering efficient solutions for business and academic needs.",
  email: "syarif@example.com",
  github_url: "https://github.com/Dunaman10",
  linkedin_url: "https://www.linkedin.com/in/syarif-h-0b5069236/?skipRedirect=true",
  fiverr_url: "https://www.fiverr.com/s/jjzVY3m",
  cv_url: "/cv.pdf",
  avatar_url: "/profil.png"
};

export const initialProjects = [
  {
    id: "1",
    title: "Zentury",
    subtitle: "FRONT-END WEB DEVELOPMENT",
    description: "Modern landing page with high-performance animations and sleek UI, built with React 19, Tailwind CSS v4, and GSAP for smooth scroll-driven interactions.",
    image_url: "/portfolio/zentury.png",
    category: "web",
    tech_stack: ["React", "Tailwind CSS", "GSAP"],
    demo_url: "https://zenturyy.vercel.app/",
    github_url: "https://github.com/Dunaman10",
    is_featured: true,
    order_index: 1
  },
  {
    id: "2",
    title: "Cute Top Up",
    subtitle: "UI/UX DESIGN",
    description: "Gaming top-up mobile app design featuring popular games like Mobile Legends, PUBG, Free Fire, and Honor of Kings.",
    image_url: "/portfolio/cute-topup.jpg",
    category: "uiux",
    tech_stack: ["Figma", "UI Design", "Mobile App"],
    demo_url: null,
    github_url: null,
    is_featured: false,
    order_index: 2
  },
  {
    id: "3",
    title: "Daruttafsir",
    subtitle: "WEB DEVELOPMENT",
    description: "Modern Islamic education website for Pondok Pesantren Darut Tafsir featuring Quranic studies, facilities showcase, and student enrollment system.",
    image_url: "/portfolio/daruttafsir.png",
    category: "web",
    tech_stack: ["Laravel", "Tailwind CSS", "MySQL"],
    demo_url: "https://daruttafsir.santriqu.id/",
    github_url: null,
    is_featured: false,
    order_index: 3
  },
  {
    id: "4",
    title: "VMS",
    subtitle: "WEB DEVELOPMENT",
    description: "Full-featured Vehicle Management System built on TALL Stack with Filament v5 admin panel, Livewire v3 real-time components, and MySQL database.",
    image_url: "/portfolio/vms.png",
    category: "web",
    tech_stack: ["Laravel 12", "Filament", "Livewire"],
    demo_url: "https://vms.laravel.cloud/",
    github_url: "https://github.com/Dunaman10",
    is_featured: false,
    order_index: 4
  },
  {
    id: "16",
    title: "NanoConnect",
    subtitle: "WEB DEVELOPMENT",
    description: "Nano influencer marketplace platform connecting Indonesian SMEs (UMKM) with nano creators (1K-20K followers) for affordable, authentic, and effective local marketing campaigns.",
    image_url: "/portfolio/nanoconnect.png",
    category: "web",
    tech_stack: ["React", "Tailwind CSS", "EdgeOne"],
    demo_url: "https://nanoconnect.edgeone.dev/",
    github_url: null,
    is_featured: false,
    order_index: 5
  },
  {
    id: "5",
    title: "Catering Mama",
    subtitle: "WEB DEVELOPMENT",
    description: "Professional catering service website offering authentic Indonesian home-cooked meals with online ordering and delivery service.",
    image_url: "/portfolio/catering-mama.png",
    category: "web",
    tech_stack: ["WordPress", "Elementor", "CSS"],
    demo_url: "https://catering-mama.netlify.app/",
    github_url: null,
    is_featured: false,
    order_index: 6
  },
  {
    id: "6",
    title: "Amir Elixir",
    subtitle: "WEB DEVELOPMENT",
    description: "Luxury perfume e-commerce platform with premium design, featuring product catalog from Contentful CMS and elegant user experience.",
    image_url: "/portfolio/amir-elixir.png",
    category: "web",
    tech_stack: ["React", "Vite", "Contentful CMS"],
    demo_url: "https://amirperfume.edgeone.dev/",
    github_url: null,
    is_featured: false,
    order_index: 7
  },
  {
    id: "7",
    title: "Movientory",
    subtitle: "WEB DEVELOPMENT",
    description: "A movie discovery platform that allows users to search through thousands of movies and explore trending titles.",
    image_url: "/portfolio/myflix.jpg",
    category: "web",
    tech_stack: ["React", "Tailwind CSS", "TMDB API"],
    demo_url: "https://movientory.vercel.app/",
    github_url: null,
    is_featured: false,
    order_index: 8
  },
  {
    id: "8",
    title: "Trendy Wear",
    subtitle: "WEB DEVELOPMENT",
    description: "A modern and stylish e-commerce landing page for a clothing brand with premium aesthetics.",
    image_url: "/portfolio/portfolio.png",
    category: "web",
    tech_stack: ["React", "Tailwind CSS"],
    demo_url: "https://trendy-wear.vercel.app/",
    github_url: null,
    is_featured: false,
    order_index: 9
  },
  {
    id: "9",
    title: "Wedding Invitation",
    subtitle: "WEB DEVELOPMENT",
    description: "A digital wedding invitation template featuring interactive elements and elegant design.",
    image_url: "/portfolio/daruttafsir.png",
    category: "web",
    tech_stack: ["HTML", "Tailwind CSS", "JavaScript"],
    demo_url: "https://wedding-invitation-six-mu.vercel.app/",
    github_url: null,
    is_featured: false,
    order_index: 10
  },
  {
    id: "10",
    title: "Company Profile",
    subtitle: "WEB DEVELOPMENT",
    description: "A professional corporate landing page showcasing services, portfolio, and contact sections.",
    image_url: "/portfolio/vms.png",
    category: "web",
    tech_stack: ["HTML", "Materialize CSS", "JavaScript"],
    demo_url: "https://company-profile-dusky.vercel.app/",
    github_url: null,
    is_featured: false,
    order_index: 11
  },
  {
    id: "11",
    title: "Flappy Bird Game",
    subtitle: "WEB DEVELOPMENT",
    description: "A web-based recreation of the classic Flappy Bird game with additional cheat features.",
    image_url: "/portfolio/at-tasawuq.jpg",
    category: "web",
    tech_stack: ["JavaScript", "HTML5 Canvas"],
    demo_url: "https://flappy-bird-five-flame.vercel.app/",
    github_url: null,
    is_featured: false,
    order_index: 12
  },
  {
    id: "12",
    title: "At-Tasawuq",
    subtitle: "UI/UX DESIGN",
    description: "E-Commerce mobile app UI design for a shoes marketplace with modern product display and seamless shopping experience.",
    image_url: "/portfolio/at-tasawuq.jpg",
    category: "uiux",
    tech_stack: ["Figma", "UI Design", "Mobile App"],
    demo_url: null,
    github_url: null,
    is_featured: false,
    order_index: 13
  },
  {
    id: "13",
    title: "HouseSpace",
    subtitle: "UI/UX DESIGN",
    description: "Real estate website design with property search functionality for finding homes, apartments, and residential properties.",
    image_url: "/portfolio/housespace.jpg",
    category: "uiux",
    tech_stack: ["Figma", "Web Design", "UI/UX"],
    demo_url: null,
    github_url: null,
    is_featured: false,
    order_index: 14
  },
  {
    id: "14",
    title: "Kopi Anak Senja",
    subtitle: "WEB DEVELOPMENT",
    description: "Coffee shop website with warm aesthetics, featuring menu showcase and beautiful landing page.",
    image_url: "/portfolio/kopi-anak-senja.jpg",
    category: "web",
    tech_stack: ["HTML", "CSS", "JavaScript"],
    demo_url: "https://kedai-kopi-anak-senja-hrvo.vercel.app/",
    github_url: null,
    is_featured: false,
    order_index: 15
  },
  {
    id: "15",
    title: "CekCrypto",
    subtitle: "WEB DEVELOPMENT",
    description: "Cryptocurrency market platform for tracking Bitcoin, Ethereum and other crypto prices with real-time data.",
    image_url: "/portfolio/cekcrypto.jpg",
    category: "web",
    tech_stack: ["HTML", "CSS", "JavaScript"],
    demo_url: "https://cekcrypto.vercel.app/",
    github_url: null,
    is_featured: false,
    order_index: 16
  }
];

export const initialSkills = [
  { id: "1", name: "Laravel", icon_url: "/laravel-logo.png", order_index: 1 },
  { id: "2", name: "Next.js", icon_url: "nextjs", order_index: 2 },
  { id: "3", name: "React JS", icon_url: "react", order_index: 3 },
  { id: "4", name: "Vue.js", icon_url: "/vue-logo.png", order_index: 4 },
  { id: "5", name: "Git", icon_url: "git", order_index: 5 },
  { id: "6", name: "Figma", icon_url: "figma", order_index: 6 },
];

export const initialCertificates = [
  {
    id: "1",
    title: "BNSP - Web Developer Specialist",
    slug: "bnsp",
    issuer: "Badan Nasional Sertifikasi Profesi (BNSP)",
    issue_date: "2024",
    credential_url: "/certificate/bnsp/Certificate-Of-Competence-BNSP.pdf",
    image_url: "/certificate/bnsp/Certificate-Of-Competence-BNSP.pdf",
    description: "Sertifikasi Kompetensi Nasional Republik Indonesia di bidang Pemrograman Web & Rekayasa Perangkat Lunak.",
    skills_learned: ["Web Architecture", "Database Design", "Web Security", "Professional Standards"],
    order_index: 1
  },
  {
    id: "2",
    title: "Codepolitan - Fullstack Web Developer Mastery",
    slug: "codepolitan",
    issuer: "Codepolitan & DevHandal",
    issue_date: "2024 - 2026",
    credential_url: "/certificate/codepolitan/Awal Menjadi Fullstack Web Developer.pdf",
    image_url: "/certificate/codepolitan/Awal Menjadi Fullstack Web Developer.pdf",
    description: "Kurikulum komprehensif menguasai ekosistem React, Node.js, Express, MongoDB, Tailwind CSS, Laravel, dan deployment cloud.",
    skills_learned: ["React.js", "Next.js", "Laravel", "REST APIs", "Modern UI/UX"],
    order_index: 2
  },
  {
    id: "3",
    title: "Dicoding - Software & Web Development Learning Path",
    slug: "dicoding",
    issuer: "Dicoding Academy Indonesia",
    issue_date: "2024",
    credential_url: "/certificate/dicoding/Belajar-Dasar-Pemrograman-Web.pdf",
    image_url: "/certificate/dicoding/Belajar-Dasar-Pemrograman-Web.pdf",
    description: "Jalur belajar fundamental rekayasa web, manajemen versi Git/GitHub, dan dasar-dasar data software engineering.",
    skills_learned: ["HTML5", "CSS3", "JavaScript", "Git & GitHub Workflow"],
    order_index: 3
  },
  {
    id: "4",
    title: "Alibaba Cloud - Generative AI & Cloud Services",
    slug: "alibaba-cloud",
    issuer: "Alibaba Cloud Academy",
    issue_date: "2024",
    credential_url: "/certificate/alibaba-cloud/Getting-to-Know-Basic-Services-of-Alibaba-Cloud.jpg",
    image_url: "/certificate/alibaba-cloud/Getting-to-Know-Basic-Services-of-Alibaba-Cloud.jpg",
    description: "Sertifikasi cloud infrastructure, microservices dasar, dan pengenalan Generative AI Model Studio.",
    skills_learned: ["Cloud Computing", "Generative AI", "Model Studio", "Serverless"],
    order_index: 4
  },
  {
    id: "5",
    title: "Google Developer Student Clubs (GDSC)",
    slug: "gdsc",
    issuer: "GDSC UIN Jakarta",
    issue_date: "2023 - 2024",
    credential_url: "/certificate/gdsc/Sertifikat-Web-Dev-GDSC-UIN-JKT.pdf",
    image_url: "/certificate/gdsc/Sertifikat-Web-Dev-GDSC-UIN-JKT.pdf",
    description: "Pelatihan teknis intensif Web Development dan perancangan UI/UX Design modern.",
    skills_learned: ["UI/UX Prototyping", "Design System", "Modern Web Tools"],
    order_index: 5
  },
  {
    id: "6",
    title: "Prakerja - Fundamental UI Design Figma",
    slug: "prakerja",
    issuer: "Kementerian Koordinator Bidang Perekonomian & Prakerja",
    issue_date: "2023",
    credential_url: "/certificate/prakerja/Sertifikat-Prakerja-Fundamental-UI-Design-dengan-Figma.pdf",
    image_url: "/certificate/prakerja/Sertifikat-Prakerja-Fundamental-UI-Design-dengan-Figma.pdf",
    description: "Perancangan antarmuka pengguna berbasis Figma untuk platform digital dan mobile e-commerce.",
    skills_learned: ["Figma", "Wireframing", "UI Typography", "Color Theory"],
    order_index: 6
  },
  {
    id: "7",
    title: "Universitas Pamulang (UNPAM) Tech Seminars",
    slug: "unpam",
    issuer: "Fakultas Ilmu Komputer UNPAM",
    issue_date: "2023 - 2024",
    credential_url: "/certificate/unpam/Masa-Depan-Web-Development.pdf",
    image_url: "/certificate/unpam/Masa-Depan-Web-Development.pdf",
    description: "Rangkaian simposium teknologi: Masa Depan Web Dev, AI & Blockchain, dan Big Data Security.",
    skills_learned: ["Emerging Tech", "Blockchain Basics", "Cyber Security Concepts"],
    order_index: 7
  }
];
